/**
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AgentAppGuidePublicApi);
  }
}(this, function(expect, AgentAppGuidePublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AgentAppGuidePublicApi.App();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('App', function() {
    it('should create an instance of App', function() {
      // uncomment below and update the code to test App
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be.a(AgentAppGuidePublicApi.App);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property appName (base name: "AppName")', function() {
      // uncomment below and update the code to test the property appName
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property packageName (base name: "PackageName")', function() {
      // uncomment below and update the code to test the property packageName
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property tokdens (base name: "Tokdens")', function() {
      // uncomment below and update the code to test the property tokdens
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property createAt (base name: "CreateAt")', function() {
      // uncomment below and update the code to test the property createAt
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

    it('should have the property updateAt (base name: "UpdateAt")', function() {
      // uncomment below and update the code to test the property updateAt
      //var instance = new AgentAppGuidePublicApi.App();
      //expect(instance).to.be();
    });

  });

}));
