# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GuideSearchResponse")

model_instance <- GuideSearchResponse$new()

test_that("data", {
  # tests for the property `data` (array[Guide])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("paging", {
  # tests for the property `paging` (Paging)

  # uncomment below to test the property
  #expect_equal(model.instance$`paging`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (array[numeric])
  # 与 data 同顺序的相似度分数

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})
