# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test App")

model_instance <- App$new()

test_that("Id", {
  # tests for the property `Id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`Id`, "EXPECTED_RESULT")
})

test_that("AppName", {
  # tests for the property `AppName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`AppName`, "EXPECTED_RESULT")
})

test_that("PackageName", {
  # tests for the property `PackageName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`PackageName`, "EXPECTED_RESULT")
})

test_that("Description", {
  # tests for the property `Description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Description`, "EXPECTED_RESULT")
})

test_that("Tokdens", {
  # tests for the property `Tokdens` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`Tokdens`, "EXPECTED_RESULT")
})

test_that("CreateAt", {
  # tests for the property `CreateAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`CreateAt`, "EXPECTED_RESULT")
})

test_that("UpdateAt", {
  # tests for the property `UpdateAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`UpdateAt`, "EXPECTED_RESULT")
})
