# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Guide")

model_instance <- Guide$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("packageName", {
  # tests for the property `packageName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`packageName`, "EXPECTED_RESULT")
})

test_that("vector", {
  # tests for the property `vector` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`vector`, "EXPECTED_RESULT")
})

test_that("action", {
  # tests for the property `action` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`action`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("tokens", {
  # tests for the property `tokens` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tokens`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("solution", {
  # tests for the property `solution` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`solution`, "EXPECTED_RESULT")
})
