# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GuideApi")

api_instance <- GuideApi$new()

test_that("GuideGet", {
  # tests for GuideGet
  # base path: https://api/v1
  # 获取 guide 列表（按关键词）
  # @param q character 搜索关键词
  # @param page integer 页码（默认 1） (optional)
  # @param limit integer 每页数量（默认 20） (optional)
  # @return [GuideListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GuideIdIdGet", {
  # tests for GuideIdIdGet
  # base path: https://api/v1
  # 获取指定 guide（按 id）
  # @param id integer 
  # @return [GuideItemResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GuidePkgPkgnameGet", {
  # tests for GuidePkgPkgnameGet
  # base path: https://api/v1
  # 获取某包名下的 guide 列表
  # @param pkgname character 
  # @param page integer 页码（默认 1） (optional)
  # @param limit integer 每页数量（默认 20） (optional)
  # @return [GuideListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GuideSearchPkgnameGet", {
  # tests for GuideSearchPkgnameGet
  # base path: https://api/v1
  # 在指定包下根据关键词搜索 guide（词向量相似度）
  # @param pkgname character 
  # @param q character 搜索关键词
  # @param page integer 页码（默认 1） (optional)
  # @param limit integer 每页数量（默认 20） (optional)
  # @return [GuideSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
