# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AppListResponse")

model_instance <- AppListResponse$new()

test_that("data", {
  # tests for the property `data` (array[App])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("paging", {
  # tests for the property `paging` (Paging)

  # uncomment below to test the property
  #expect_equal(model.instance$`paging`, "EXPECTED_RESULT")
})
