/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param packageName 
 * @param vector 
 * @param action 
 * @param description 
 * @param tokens 
 * @param source 
 * @param solution 
 */


data class Guide (

    @Json(name = "id")
    val id: kotlin.Long,

    @Json(name = "packageName")
    val packageName: kotlin.String,

    @Json(name = "vector")
    val vector: kotlin.Any?,

    @Json(name = "action")
    val action: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "tokens")
    val tokens: kotlin.Int,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "solution")
    val solution: kotlin.String

) {


}

