# coding: utf-8

"""
    Agent App & Guide Public API

    基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agent-context-sdk.models.paging import Paging

class TestPaging(unittest.TestCase):
    """Paging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Paging:
        """Test Paging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Paging`
        """
        model = Paging()
        if include_optional:
            return Paging(
                limit = 56,
                page = 56,
                total = 56,
                kw = ''
            )
        else:
            return Paging(
                limit = 56,
                page = 56,
                total = 56,
        )
        """

    def testPaging(self):
        """Test Paging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
