# coding: utf-8

"""
    Agent App & Guide Public API

    基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agent-context-sdk.api.guide_api import GuideApi


class TestGuideApi(unittest.TestCase):
    """GuideApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GuideApi()

    def tearDown(self) -> None:
        pass

    def test_guide_get(self) -> None:
        """Test case for guide_get

        获取 guide 列表（按关键词）
        """
        pass

    def test_guide_id_id_get(self) -> None:
        """Test case for guide_id_id_get

        获取指定 guide（按 id）
        """
        pass

    def test_guide_pkg_pkgname_get(self) -> None:
        """Test case for guide_pkg_pkgname_get

        获取某包名下的 guide 列表
        """
        pass

    def test_guide_search_pkgname_get(self) -> None:
        """Test case for guide_search_pkgname_get

        在指定包下根据关键词搜索 guide（词向量相似度）
        """
        pass


if __name__ == '__main__':
    unittest.main()
