/*
 * Agent App & Guide Public API
 *
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using agent-context-sdk.Model;
using agent-context-sdk.Client;
using System.Reflection;

namespace agent-context-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GuideSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GuideSearchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GuideSearchResponse
        //private GuideSearchResponse instance;

        public GuideSearchResponseTests()
        {
            // TODO uncomment below to create an instance of GuideSearchResponse
            //instance = new GuideSearchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GuideSearchResponse
        /// </summary>
        [Fact]
        public void GuideSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GuideSearchResponse
            //Assert.IsType<GuideSearchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Paging'
        /// </summary>
        [Fact]
        public void PagingTest()
        {
            // TODO unit test for the property 'Paging'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
    }
}
