/*
Agent App & Guide Public API

基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GuideItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuideItemResponse{}

// GuideItemResponse struct for GuideItemResponse
type GuideItemResponse struct {
	Data Guide `json:"data"`
}

type _GuideItemResponse GuideItemResponse

// NewGuideItemResponse instantiates a new GuideItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuideItemResponse(data Guide) *GuideItemResponse {
	this := GuideItemResponse{}
	this.Data = data
	return &this
}

// NewGuideItemResponseWithDefaults instantiates a new GuideItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuideItemResponseWithDefaults() *GuideItemResponse {
	this := GuideItemResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GuideItemResponse) GetData() Guide {
	if o == nil {
		var ret Guide
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GuideItemResponse) GetDataOk() (*Guide, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GuideItemResponse) SetData(v Guide) {
	o.Data = v
}

func (o GuideItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuideItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GuideItemResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGuideItemResponse := _GuideItemResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGuideItemResponse)

	if err != nil {
		return err
	}

	*o = GuideItemResponse(varGuideItemResponse)

	return err
}

type NullableGuideItemResponse struct {
	value *GuideItemResponse
	isSet bool
}

func (v NullableGuideItemResponse) Get() *GuideItemResponse {
	return v.value
}

func (v *NullableGuideItemResponse) Set(val *GuideItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuideItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuideItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuideItemResponse(val *GuideItemResponse) *NullableGuideItemResponse {
	return &NullableGuideItemResponse{value: val, isSet: true}
}

func (v NullableGuideItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuideItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


