/*
Agent App & Guide Public API

基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GuideListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuideListResponse{}

// GuideListResponse struct for GuideListResponse
type GuideListResponse struct {
	Data []Guide `json:"data"`
	Paging Paging `json:"paging"`
}

type _GuideListResponse GuideListResponse

// NewGuideListResponse instantiates a new GuideListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuideListResponse(data []Guide, paging Paging) *GuideListResponse {
	this := GuideListResponse{}
	this.Data = data
	this.Paging = paging
	return &this
}

// NewGuideListResponseWithDefaults instantiates a new GuideListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuideListResponseWithDefaults() *GuideListResponse {
	this := GuideListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GuideListResponse) GetData() []Guide {
	if o == nil {
		var ret []Guide
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GuideListResponse) GetDataOk() ([]Guide, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GuideListResponse) SetData(v []Guide) {
	o.Data = v
}

// GetPaging returns the Paging field value
func (o *GuideListResponse) GetPaging() Paging {
	if o == nil {
		var ret Paging
		return ret
	}

	return o.Paging
}

// GetPagingOk returns a tuple with the Paging field value
// and a boolean to check if the value has been set.
func (o *GuideListResponse) GetPagingOk() (*Paging, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Paging, true
}

// SetPaging sets field value
func (o *GuideListResponse) SetPaging(v Paging) {
	o.Paging = v
}

func (o GuideListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuideListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["paging"] = o.Paging
	return toSerialize, nil
}

func (o *GuideListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"paging",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGuideListResponse := _GuideListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGuideListResponse)

	if err != nil {
		return err
	}

	*o = GuideListResponse(varGuideListResponse)

	return err
}

type NullableGuideListResponse struct {
	value *GuideListResponse
	isSet bool
}

func (v NullableGuideListResponse) Get() *GuideListResponse {
	return v.value
}

func (v *NullableGuideListResponse) Set(val *GuideListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuideListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuideListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuideListResponse(val *GuideListResponse) *NullableGuideListResponse {
	return &NullableGuideListResponse{value: val, isSet: true}
}

func (v NullableGuideListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuideListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


