/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import agent-context-sdk.models.ErrorResponse

class ErrorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorResponse
        //val modelInstance = ErrorResponse()

        // to test the property `error` - 错误原因
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
