/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import agent-context-sdk.models.GuideListResponse
import agent-context-sdk.models.Guide
import agent-context-sdk.models.Paging

class GuideListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuideListResponse
        //val modelInstance = GuideListResponse()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `paging`
        should("test paging") {
            // uncomment below to test the property
            //modelInstance.paging shouldBe ("TODO")
        }

    }
}
