/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.AppListResponse
import org.openapitools.client.models.App
import org.openapitools.client.models.Paging

class AppListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppListResponse
        //val modelInstance = AppListResponse()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `paging`
        should("test paging") {
            // uncomment below to test the property
            //modelInstance.paging shouldBe ("TODO")
        }

    }
}
