/*
 * Agent App & Guide Public API
 *
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct App {
    #[serde(rename = "Id")]
    pub id: i32,
    #[serde(rename = "AppName")]
    pub app_name: String,
    #[serde(rename = "PackageName")]
    pub package_name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "Tokdens")]
    pub tokdens: i32,
    #[serde(rename = "CreateAt")]
    pub create_at: String,
    #[serde(rename = "UpdateAt")]
    pub update_at: String,
}

impl App {
    pub fn new(id: i32, app_name: String, package_name: String, description: String, tokdens: i32, create_at: String, update_at: String) -> App {
        App {
            id,
            app_name,
            package_name,
            description,
            tokdens,
            create_at,
            update_at,
        }
    }
}

