=begin
#Agent App & Guide Public API

#基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/app'
require 'openapi_client/models/app_item_response'
require 'openapi_client/models/app_list_response'
require 'openapi_client/models/error_response'
require 'openapi_client/models/guide'
require 'openapi_client/models/guide_item_response'
require 'openapi_client/models/guide_list_response'
require 'openapi_client/models/guide_search_response'
require 'openapi_client/models/paging'

# APIs
require 'openapi_client/api/app_api'
require 'openapi_client/api/guide_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
