/*
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GuideItemResponse;
import org.openapitools.client.model.GuideListResponse;
import org.openapitools.client.model.GuideSearchResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GuideApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GuideApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GuideApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for guideGet
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideGetCall(@javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/guide";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (q != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("q", q));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call guideGetValidateBeforeCall(@javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'q' is set
        if (q == null) {
            throw new ApiException("Missing the required parameter 'q' when calling guideGet(Async)");
        }

        return guideGetCall(q, page, limit, _callback);

    }

    /**
     * 获取 guide 列表（按关键词）
     * 
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return GuideListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public GuideListResponse guideGet(@javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<GuideListResponse> localVarResp = guideGetWithHttpInfo(q, page, limit);
        return localVarResp.getData();
    }

    /**
     * 获取 guide 列表（按关键词）
     * 
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return ApiResponse&lt;GuideListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GuideListResponse> guideGetWithHttpInfo(@javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = guideGetValidateBeforeCall(q, page, limit, null);
        Type localVarReturnType = new TypeToken<GuideListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取 guide 列表（按关键词） (asynchronously)
     * 
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideGetAsync(@javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<GuideListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = guideGetValidateBeforeCall(q, page, limit, _callback);
        Type localVarReturnType = new TypeToken<GuideListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for guideIdIdGet
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideIdIdGetCall(@javax.annotation.Nonnull Long id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/guide/id/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call guideIdIdGetValidateBeforeCall(@javax.annotation.Nonnull Long id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling guideIdIdGet(Async)");
        }

        return guideIdIdGetCall(id, _callback);

    }

    /**
     * 获取指定 guide（按 id）
     * 
     * @param id  (required)
     * @return GuideItemResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public GuideItemResponse guideIdIdGet(@javax.annotation.Nonnull Long id) throws ApiException {
        ApiResponse<GuideItemResponse> localVarResp = guideIdIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 获取指定 guide（按 id）
     * 
     * @param id  (required)
     * @return ApiResponse&lt;GuideItemResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GuideItemResponse> guideIdIdGetWithHttpInfo(@javax.annotation.Nonnull Long id) throws ApiException {
        okhttp3.Call localVarCall = guideIdIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<GuideItemResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取指定 guide（按 id） (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideIdIdGetAsync(@javax.annotation.Nonnull Long id, final ApiCallback<GuideItemResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = guideIdIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<GuideItemResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for guidePkgPkgnameGet
     * @param pkgname  (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guidePkgPkgnameGetCall(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/guide/pkg/{pkgname}"
            .replace("{" + "pkgname" + "}", localVarApiClient.escapeString(pkgname.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call guidePkgPkgnameGetValidateBeforeCall(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pkgname' is set
        if (pkgname == null) {
            throw new ApiException("Missing the required parameter 'pkgname' when calling guidePkgPkgnameGet(Async)");
        }

        return guidePkgPkgnameGetCall(pkgname, page, limit, _callback);

    }

    /**
     * 获取某包名下的 guide 列表
     * 
     * @param pkgname  (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return GuideListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public GuideListResponse guidePkgPkgnameGet(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<GuideListResponse> localVarResp = guidePkgPkgnameGetWithHttpInfo(pkgname, page, limit);
        return localVarResp.getData();
    }

    /**
     * 获取某包名下的 guide 列表
     * 
     * @param pkgname  (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return ApiResponse&lt;GuideListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GuideListResponse> guidePkgPkgnameGetWithHttpInfo(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = guidePkgPkgnameGetValidateBeforeCall(pkgname, page, limit, null);
        Type localVarReturnType = new TypeToken<GuideListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 获取某包名下的 guide 列表 (asynchronously)
     * 
     * @param pkgname  (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guidePkgPkgnameGetAsync(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<GuideListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = guidePkgPkgnameGetValidateBeforeCall(pkgname, page, limit, _callback);
        Type localVarReturnType = new TypeToken<GuideListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for guideSearchPkgnameGet
     * @param pkgname  (required)
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideSearchPkgnameGetCall(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/guide/search/{pkgname}"
            .replace("{" + "pkgname" + "}", localVarApiClient.escapeString(pkgname.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (q != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("q", q));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call guideSearchPkgnameGetValidateBeforeCall(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'pkgname' is set
        if (pkgname == null) {
            throw new ApiException("Missing the required parameter 'pkgname' when calling guideSearchPkgnameGet(Async)");
        }

        // verify the required parameter 'q' is set
        if (q == null) {
            throw new ApiException("Missing the required parameter 'q' when calling guideSearchPkgnameGet(Async)");
        }

        return guideSearchPkgnameGetCall(pkgname, q, page, limit, _callback);

    }

    /**
     * 在指定包下根据关键词搜索 guide（词向量相似度）
     * 
     * @param pkgname  (required)
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return GuideSearchResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public GuideSearchResponse guideSearchPkgnameGet(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        ApiResponse<GuideSearchResponse> localVarResp = guideSearchPkgnameGetWithHttpInfo(pkgname, q, page, limit);
        return localVarResp.getData();
    }

    /**
     * 在指定包下根据关键词搜索 guide（词向量相似度）
     * 
     * @param pkgname  (required)
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @return ApiResponse&lt;GuideSearchResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GuideSearchResponse> guideSearchPkgnameGetWithHttpInfo(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit) throws ApiException {
        okhttp3.Call localVarCall = guideSearchPkgnameGetValidateBeforeCall(pkgname, q, page, limit, null);
        Type localVarReturnType = new TypeToken<GuideSearchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * 在指定包下根据关键词搜索 guide（词向量相似度） (asynchronously)
     * 
     * @param pkgname  (required)
     * @param q 搜索关键词 (required)
     * @param page 页码（默认 1） (optional, default to 1)
     * @param limit 每页数量（默认 20） (optional, default to 20)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> 成功 </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> 统一错误 </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call guideSearchPkgnameGetAsync(@javax.annotation.Nonnull String pkgname, @javax.annotation.Nonnull String q, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer limit, final ApiCallback<GuideSearchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = guideSearchPkgnameGetValidateBeforeCall(pkgname, q, page, limit, _callback);
        Type localVarReturnType = new TypeToken<GuideSearchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
