/*
Agent App & Guide Public API

Testing GuideAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_GuideAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GuideAPIService GuideGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GuideAPI.GuideGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GuideAPIService GuideIdIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int64

		resp, httpRes, err := apiClient.GuideAPI.GuideIdIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GuideAPIService GuidePkgPkgnameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkgname string

		resp, httpRes, err := apiClient.GuideAPI.GuidePkgPkgnameGet(context.Background(), pkgname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GuideAPIService GuideSearchPkgnameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var pkgname string

		resp, httpRes, err := apiClient.GuideAPI.GuideSearchPkgnameGet(context.Background(), pkgname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
