/**
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Guide from './Guide';
import Paging from './Paging';

/**
 * The GuideListResponse model module.
 * @module model/GuideListResponse
 * @version 1.0.0
 */
class GuideListResponse {
    /**
     * Constructs a new <code>GuideListResponse</code>.
     * @alias module:model/GuideListResponse
     * @param data {Array.<module:model/Guide>} 
     * @param paging {module:model/Paging} 
     */
    constructor(data, paging) { 
        
        GuideListResponse.initialize(this, data, paging);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, paging) { 
        obj['data'] = data;
        obj['paging'] = paging;
    }

    /**
     * Constructs a <code>GuideListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GuideListResponse} obj Optional instance to populate.
     * @return {module:model/GuideListResponse} The populated <code>GuideListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GuideListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Guide]);
            }
            if (data.hasOwnProperty('paging')) {
                obj['paging'] = Paging.constructFromObject(data['paging']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GuideListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GuideListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GuideListResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Guide.validateJSON(item);
            };
        }
        // validate the optional field `paging`
        if (data['paging']) { // data not null
          Paging.validateJSON(data['paging']);
        }

        return true;
    }


}

GuideListResponse.RequiredProperties = ["data", "paging"];

/**
 * @member {Array.<module:model/Guide>} data
 */
GuideListResponse.prototype['data'] = undefined;

/**
 * @member {module:model/Paging} paging
 */
GuideListResponse.prototype['paging'] = undefined;






export default GuideListResponse;

