/**
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Paging model module.
 * @module model/Paging
 * @version 1.0.0
 */
class Paging {
    /**
     * Constructs a new <code>Paging</code>.
     * @alias module:model/Paging
     * @param limit {Number} 
     * @param page {Number} 
     * @param total {Number} 
     */
    constructor(limit, page, total) { 
        
        Paging.initialize(this, limit, page, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, limit, page, total) { 
        obj['limit'] = limit;
        obj['page'] = page;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>Paging</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Paging} obj Optional instance to populate.
     * @return {module:model/Paging} The populated <code>Paging</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Paging();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('kw')) {
                obj['kw'] = ApiClient.convertToType(data['kw'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Paging</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Paging</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Paging.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kw'] && !(typeof data['kw'] === 'string' || data['kw'] instanceof String)) {
            throw new Error("Expected the field `kw` to be a primitive type in the JSON string but got " + data['kw']);
        }

        return true;
    }


}

Paging.RequiredProperties = ["limit", "page", "total"];

/**
 * @member {Number} limit
 */
Paging.prototype['limit'] = undefined;

/**
 * @member {Number} page
 */
Paging.prototype['page'] = undefined;

/**
 * @member {Number} total
 */
Paging.prototype['total'] = undefined;

/**
 * 可选，搜索关键词回显
 * @member {String} kw
 */
Paging.prototype['kw'] = undefined;






export default Paging;

