/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param appName 
 * @param packageName 
 * @param description 
 * @param tokdens 
 * @param createAt 
 * @param updateAt 
 */


data class App (

    @Json(name = "Id")
    val id: kotlin.Int,

    @Json(name = "AppName")
    val appName: kotlin.String,

    @Json(name = "PackageName")
    val packageName: kotlin.String,

    @Json(name = "Description")
    val description: kotlin.String,

    @Json(name = "Tokdens")
    val tokdens: kotlin.Int,

    @Json(name = "CreateAt")
    val createAt: java.time.OffsetDateTime,

    @Json(name = "UpdateAt")
    val updateAt: java.time.OffsetDateTime

) {


}

