/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.models

import agent-context-sdk.models.App
import agent-context-sdk.models.Paging

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param paging 
 */


data class AppListResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<App>,

    @Json(name = "paging")
    val paging: Paging

) {


}

