/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param limit 
 * @param page 
 * @param total 
 * @param kw 可选，搜索关键词回显
 */


data class Paging (

    @Json(name = "limit")
    val limit: kotlin.Int,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "total")
    val total: kotlin.Int,

    /* 可选，搜索关键词回显 */
    @Json(name = "kw")
    val kw: kotlin.String? = null

) {


}

