/*
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AppItemResponse;
import org.openapitools.client.model.AppListResponse;
import org.openapitools.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppApi
 */
@Disabled
public class AppApiTest {

    private final AppApi api = new AppApi();

    /**
     * 获取 app 列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appGetTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        AppListResponse response = api.appGet(page, limit);
        // TODO: test validations
    }

    /**
     * 获取指定 app 信息（按 id）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appIdIdGetTest() throws ApiException {
        Integer id = null;
        AppItemResponse response = api.appIdIdGet(id);
        // TODO: test validations
    }

    /**
     * 获取指定 app 信息（按包名）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appPkgPkgnameGetTest() throws ApiException {
        String pkgname = null;
        AppItemResponse response = api.appPkgPkgnameGet(pkgname);
        // TODO: test validations
    }

    /**
     * 搜索 app
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appSearchGetTest() throws ApiException {
        String q = null;
        Integer page = null;
        Integer limit = null;
        AppListResponse response = api.appSearchGet(q, page, limit);
        // TODO: test validations
    }

}
