/*
 * Agent App & Guide Public API
 * 基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.GuideItemResponse;
import org.openapitools.client.model.GuideListResponse;
import org.openapitools.client.model.GuideSearchResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GuideApi
 */
@Disabled
public class GuideApiTest {

    private final GuideApi api = new GuideApi();

    /**
     * 获取 guide 列表（按关键词）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void guideGetTest() throws ApiException {
        String q = null;
        Integer page = null;
        Integer limit = null;
        GuideListResponse response = api.guideGet(q, page, limit);
        // TODO: test validations
    }

    /**
     * 获取指定 guide（按 id）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void guideIdIdGetTest() throws ApiException {
        Long id = null;
        GuideItemResponse response = api.guideIdIdGet(id);
        // TODO: test validations
    }

    /**
     * 获取某包名下的 guide 列表
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void guidePkgPkgnameGetTest() throws ApiException {
        String pkgname = null;
        Integer page = null;
        Integer limit = null;
        GuideListResponse response = api.guidePkgPkgnameGet(pkgname, page, limit);
        // TODO: test validations
    }

    /**
     * 在指定包下根据关键词搜索 guide（词向量相似度）
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void guideSearchPkgnameGetTest() throws ApiException {
        String pkgname = null;
        String q = null;
        Integer page = null;
        Integer limit = null;
        GuideSearchResponse response = api.guideSearchPkgnameGet(pkgname, q, page, limit);
        // TODO: test validations
    }

}
