=begin
#Agent App & Guide Public API

#基本地址：`/v1/`（已在 servers 配置） - 普通接口 **无鉴权** - 统一错误：`{\"error\":\"reason\"}` - 分页：`page` 默认 1，`limit` 默认 20 - `score` 为相似度（仅 /guide/search/{pkgname} 返回） 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AppApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AppApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AppApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AppApi' do
    it 'should create an instance of AppApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AppApi)
    end
  end

  # unit tests for app_get
  # 获取 app 列表
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 页码（默认 1）
  # @option opts [Integer] :limit 每页数量（默认 20）
  # @return [AppListResponse]
  describe 'app_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for app_id_id_get
  # 获取指定 app 信息（按 id）
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [AppItemResponse]
  describe 'app_id_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for app_pkg_pkgname_get
  # 获取指定 app 信息（按包名）
  # @param pkgname 
  # @param [Hash] opts the optional parameters
  # @return [AppItemResponse]
  describe 'app_pkg_pkgname_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for app_search_get
  # 搜索 app
  # @param q 搜索关键词
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 页码（默认 1）
  # @option opts [Integer] :limit 每页数量（默认 20）
  # @return [AppListResponse]
  describe 'app_search_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
