/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package agent-context-sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import agent-context-sdk.apis.GuideApi
import agent-context-sdk.models.ErrorResponse
import agent-context-sdk.models.GuideItemResponse
import agent-context-sdk.models.GuideListResponse
import agent-context-sdk.models.GuideSearchResponse

class GuideApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GuideApi
        //val apiInstance = GuideApi()

        // to test guideGet
        should("test guideGet") {
            // uncomment below to test guideGet
            //val q : kotlin.String = q_example // kotlin.String | 搜索关键词
            //val page : kotlin.Int = 56 // kotlin.Int | 页码（默认 1）
            //val limit : kotlin.Int = 56 // kotlin.Int | 每页数量（默认 20）
            //val result : GuideListResponse = apiInstance.guideGet(q, page, limit)
            //result shouldBe ("TODO")
        }

        // to test guideIdIdGet
        should("test guideIdIdGet") {
            // uncomment below to test guideIdIdGet
            //val id : kotlin.Long = 789 // kotlin.Long | 
            //val result : GuideItemResponse = apiInstance.guideIdIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test guidePkgPkgnameGet
        should("test guidePkgPkgnameGet") {
            // uncomment below to test guidePkgPkgnameGet
            //val pkgname : kotlin.String = pkgname_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 页码（默认 1）
            //val limit : kotlin.Int = 56 // kotlin.Int | 每页数量（默认 20）
            //val result : GuideListResponse = apiInstance.guidePkgPkgnameGet(pkgname, page, limit)
            //result shouldBe ("TODO")
        }

        // to test guideSearchPkgnameGet
        should("test guideSearchPkgnameGet") {
            // uncomment below to test guideSearchPkgnameGet
            //val pkgname : kotlin.String = pkgname_example // kotlin.String | 
            //val q : kotlin.String = q_example // kotlin.String | 搜索关键词
            //val page : kotlin.Int = 56 // kotlin.Int | 页码（默认 1）
            //val limit : kotlin.Int = 56 // kotlin.Int | 每页数量（默认 20）
            //val result : GuideSearchResponse = apiInstance.guideSearchPkgnameGet(pkgname, q, page, limit)
            //result shouldBe ("TODO")
        }

    }
}
